/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.srbn.GUI;

import com.srbn.Lexer.Lexer;
import com.srbn.obj.Query;
import com.srbn.Parser.Parser;
import com.srbn.utils.GUIMagnament.JtreeManager;
import java.io.File;
import java.io.StringReader;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ADMIN
 */
public class SQLideMainUI extends javax.swing.JFrame {

    JtreeManager jtr = new JtreeManager();
    String ActualFold;
    /**
     * Creates new form SQLideMainUI
     */

    public SQLideMainUI() {
        initComponents();
        setLocationRelativeTo(null);
        filesTree.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filesTreePane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filesTree = new javax.swing.JTree();
        SourceScrollPane = new javax.swing.JScrollPane();
        sourceCodeTextArea = new javax.swing.JTextArea();
        CSVscrollPane = new javax.swing.JScrollPane();
        csvTextArea = new javax.swing.JTextArea();
        executeButton = new javax.swing.JButton();
        buttonsFilesPane = new javax.swing.JPanel();
        openFileButton = new javax.swing.JButton();
        newFileButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filesTreePane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        filesTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(filesTree);

        javax.swing.GroupLayout filesTreePaneLayout = new javax.swing.GroupLayout(filesTreePane);
        filesTreePane.setLayout(filesTreePaneLayout);
        filesTreePaneLayout.setHorizontalGroup(
            filesTreePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        filesTreePaneLayout.setVerticalGroup(
            filesTreePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        SourceScrollPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sourceCodeTextArea.setColumns(20);
        sourceCodeTextArea.setRows(5);
        SourceScrollPane.setViewportView(sourceCodeTextArea);

        csvTextArea.setEditable(false);
        csvTextArea.setColumns(20);
        csvTextArea.setLineWrap(true);
        csvTextArea.setRows(5);
        csvTextArea.setTabSize(10);
        CSVscrollPane.setViewportView(csvTextArea);

        executeButton.setText("Execute");
        executeButton.setToolTipText("");
        executeButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });

        buttonsFilesPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        openFileButton.setText("Open");
        openFileButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        newFileButton.setText("NewFile");
        newFileButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        newFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileButtonActionPerformed(evt);
            }
        });

        saveButton.setText("NewFolder");
        saveButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout buttonsFilesPaneLayout = new javax.swing.GroupLayout(buttonsFilesPane);
        buttonsFilesPane.setLayout(buttonsFilesPaneLayout);
        buttonsFilesPaneLayout.setHorizontalGroup(
            buttonsFilesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsFilesPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonsFilesPaneLayout.setVerticalGroup(
            buttonsFilesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsFilesPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonsFilesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newFileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openFileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filesTreePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonsFilesPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(executeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CSVscrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SourceScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonsFilesPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filesTreePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(CSVscrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SourceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(executeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        try {
            StringReader sr = new StringReader(sourceCodeTextArea.getText());
            Lexer lex = new Lexer(new StringReader(sourceCodeTextArea.getText()));
            Parser sintax = new Parser(lex);
            Query query = (Query) sintax.parse().value;
            query.printQueries();
        } catch (Exception e) {
            System.out.println("----> " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_executeButtonActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        JFrame frame = new JFrame("File Tree Example");
        frame.setSize(400, 300);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        int result = fileChooser.showOpenDialog(frame);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFolder = fileChooser.getSelectedFile();
            ActualFold = selectedFolder.getPath();
            DefaultMutableTreeNode rootNode = jtr.createFileTree(selectedFolder);
            DefaultTreeModel treeModel = new DefaultTreeModel(rootNode);
            jtr.addSelectionNodes(filesTree, csvTextArea, ActualFold);
            filesTree.setModel(treeModel);
            filesTree.setVisible(true);
        }
    }//GEN-LAST:event_openFileButtonActionPerformed
    
    private void newFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileButtonActionPerformed
        
        
        
    }//GEN-LAST:event_newFileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CSVscrollPane;
    private javax.swing.JScrollPane SourceScrollPane;
    private javax.swing.JPanel buttonsFilesPane;
    private javax.swing.JTextArea csvTextArea;
    private javax.swing.JButton executeButton;
    private javax.swing.JTree filesTree;
    private javax.swing.JPanel filesTreePane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newFileButton;
    private javax.swing.JButton openFileButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea sourceCodeTextArea;
    // End of variables declaration//GEN-END:variables
}
